@extends('layouts.app')

@section('content')
<div class="breadcrumb__area breadcrumb-space overflow-hidden banner-home-bg ">
    <div class="banner-home__middel-shape inner-top-shape"></div>
    <div class="container">
        <div class="banner-all-shape-wrapper">
            <div class="banner-home__banner-shape-1 first-shape">
                <img class="upDown-top" src="{{ asset('assets/imgs/banner-1/banner-shape-1.svg')}}" alt="img not found">
            </div>
            <div class="banner-home__banner-shape-2 second-shape">
                <img class="upDown-bottom" src="{{ asset('assets/imgs/banner-1/banner-shape-2.svg')}}" alt="img not found">
            </div>
            <div class="right-shape">
                <img class="zooming" src="{{ asset('assets/imgs/inner-img/inner-right-shape.svg')}}" alt="img not found">
            </div>
        </div>
        <div class="row align-items-center justify-content-between">
            <div class="col-12">
                <div class="breadcrumb__content text-center">
                    <div class="breadcrumb__title-wrapper mb-15 mb-sm-10 mb-xs-5">
                        <h1 class="breadcrumb__title color-white wow fadeIn animated" data-wow-delay=".1s">Services</h1>
                    </div>
                    <div class="breadcrumb__menu wow fadeIn animated" data-wow-delay=".5s">
                        <nav>
                            <ul>
                                <li><span><a href="#!">Home</a></span></li>
                                <li><span><a href="{{ route('service-equipment-printing.index') }}">Services</a></span></li>
                                <li class="active"><span>{{ $page_title }}</span></li>
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- portfolio-details area start -->
<section class="section-space portfolio-details__area service-details__area">
    <div class="container">
        <div class="row">
            <div class="col-xl-8">
                <div class="service-details-content">
                    <div class="service-details-content-thumb mb-25">
                         <img src="{{ asset('assets/imgs/ppi-img/service/ablative-film/ablative-film-2.jpg')}}" alt="image not found" class="img-fluid" style="max-height: 35vh !important;">
                    </div>

                    <h2 class="service-details-content-title mb-10">Ablative Film</h2>

                    <p>Our Ablative Film is designed for high-precision printing applications that require exceptional detail and accuracy. Ideal for use in laser etching and engraving, ablative film creates crisp, clear designs by selectively removing material from the film layer. This technology allows for intricate patterns and precise details, making it an excellent choice for industrial and specialized printing processes.</p>

                    <p>With superior heat resistance and high-definition capabilities, ablative film ensures consistent performance and high-quality output for demanding applications.</p>

                    {{-- <h4 class="service-details-content-title">Product Base Film</h4>
                    <div class="latest-about2__content-text">
                        <ul>
                            <li><i class="fa-solid fa-circle-dot"></i>Base Film 1100 x 150 m</li>
                            <li><i class="fa-solid fa-circle-dot"></i>Base Film 1420 x 150 m</li>
                        </ul>
                    </div> --}}

                    <div class="middel-img d-flex">
                        <img src="{{ asset('assets/imgs/ppi-img/service/ablative-film/ablative-film-1.jpeg')}}" alt="img not found" style="max-width: 35vh !important;">
                        <img src="{{ asset('assets/imgs/ppi-img/service/ablative-film/ablative-film-3.png')}}" alt="img not found" style="max-width: 35vh !important;">
                    </div>
                    <h2 class="service-details-content-title">Why Choose Ablative Film?</h2>
                    <p>Our ablative film is engineered for applications that require precision and durability, making it ideal for businesses needing intricate designs with reliable performance.</p>

                    <div class="latest-about2__content-text">
                        <ul>
                            <li><i class="fa-solid fa-check"></i>High Precision: Produces sharp, detailed patterns with laser accuracy.</li>
                            <li><i class="fa-solid fa-check"></i>Heat Resistance: Built to withstand the heat generated by laser engraving processes.</li>
                            <li><i class="fa-solid fa-check"></i>Consistent Quality: Delivers reliable performance and uniform results in each application.</li>
                            <li><i class="fa-solid fa-check"></i>Ideal for Specialized Applications: Suitable for industrial etching, engraving, and high-detail designs.</li>
                        </ul>
                    </div>

                    <h2 class="service-details-content-title">Project Tips</h2>
                    <p>For the best results when using ablative film, consider the following tips:</p>

                    <div class="latest-about2__content-text">
                        <ul>
                            <li><i class="fa-solid fa-check"></i>Ensure laser equipment is calibrated accurately to maximize detail and precision.</li>
                            <li><i class="fa-solid fa-check"></i>Use appropriate power settings on the laser to prevent over-etching or damage.</li>
                            <li><i class="fa-solid fa-check"></i>Handle the film carefully to avoid scratches or marks before processing.</li>
                            <li><i class="fa-solid fa-check"></i>Store the film in a dust-free environment to maintain its quality and clarity.</li>
                        </ul>
                    </div>
                </div>

                <h2 class="service-details-content-title">Overview & Challenge</h2>
                <p>Ablative film is perfect for high-precision, high-detail printing projects, especially where laser engraving is required. The challenge lies in maintaining precise laser calibration and handling techniques to ensure consistent quality without damaging the film.</p>
                <p>By choosing our ablative film, you ensure your projects are supported by high-quality, reliable materials for the most detailed and durable results.</p>
            </div>
            <div class="col-xl-4">
                <div class="service-details-right">
                    <div class="service-details-righ-widget">
                        <h5 class="title">Other Services</h5>

                        <div class="search">
                            <a href="{{ route('service-equipment-printing.base-film') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>Base Film</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                            <a href="{{ route('service-equipment-printing.bopp-film') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>BOPP Film</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                            <a href="{{ route('service-equipment-printing.astralon') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>Astralon</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                            <a href="{{ route('service-equipment-printing.stripping-stopper') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>Stripping / Stopper</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                            <a href="{{ route('service-equipment-printing.bonding-machine') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>Bonding Machine</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                            <a href="{{ route('service-equipment-printing.ablative-film') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>Ablative Film</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                            <a href="{{ route('service-equipment-printing.digital-solid') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>Digital Solid</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                            <a href="{{ route('service-equipment-printing.letter-press') }}">
                                <div class="search-bar main-search d-flex mb-20">
                                    <h6>Letter Press</h6>
                                    <span>
                                        <i class="fa-solid fa-angle-right"></i>
                                    </span>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- portfolio-details area end -->
@endsection
